
example:
 property: "I AM IN THE DEFAULT"

spring:
 jpa:
   database: "MYSQL"
   show-sql: "true"
   properties:
     hibernate:
       dialect: "org.hibernate.dialect.MySQL5Dialect"
 datasource:
   platform:  "mysql"
   url: "jdbc:mysql://192.168.0.96:3306/testdb?autoReconnect=true&useSSL=false"
   username: "gain"
   password: "1234"
   dbcp2:
     test-on-borrow: true
     validation-query: "SELECT 1"
     driver: "com.mysql.cj.jdbc.Driver"
     test-while-idle: true

management:
  #  server:
  #  port: 8081
  endpoints:
    web:
      exposure:
        include: env,beans,mappings
#        include: “*”